#!/bin/bash

set -e

if [ "$#" != "1" ]; then
	echo "Usage: ruby-build-wrapper <definition>" >&2
	exit 1
fi

BASEDIR="/usr/local/lib/rubies/${1}"

if [ -e "${BASEDIR}/${1}/environment.sh" ]; then
	# We're already built, yippee!
	exit 0
fi

/usr/local/bin/ruby-build "$1" "$BASEDIR"

cat <<EOF >"${BASEDIR}/environment.sh"
PATH="${BASEDIR}/bin:\$PATH"; export PATH
RUBY_VERSION="$1"; export RUBY_VERSION
GEM_HOME="$BASEDIR"; export GEM_HOME
GEM_PATH="$BASEDIR"; export GEM_PATH
MY_RUBY_HOME="$BASEDIR"; export MY_RUBY_HOME
EOF

if [[ "$1" =~ ^maglev ]]; then
	cat <<EOF >>"${BASEDIR}/environment.sh"
MAGLEV_HOME="$BASEDIR"; export MAGLEV_HOME 
GEMSTONE_GLOBAL_DIR="$BASEDIR"; export GEMSTONE_GLOBAL_DIR
EOF
else
	cat <<EOF >>"${BASEDIR}/environment.sh"
unset MAGLEV_HOME
unset GEMSTONE_GLOBAL_DIR
EOF
fi

# Let's test this out with a bundler install...
source "${BASEDIR}/environment.sh"

gem install bundler
