#!/bin/bash

set -e

if [ "$#" != "1" ]; then
	echo "Usage: ruby-build-wrapper <definition>" >&2
	exit 1
fi

# Make sure someone isn't trying to do the dodgy on us by specifying a
# version definition that would cause us to read /etc/shadow or something
pushd /usr/local/share/ruby-build >/dev/null
if ! ls -1 | grep -Fxq "$1"; then
	echo "No such available Ruby: ${1}" >&2
	exit 1
fi
popd >/dev/null

BASEDIR="/usr/local/lib/rubies/${1}"

if [ -e "${BASEDIR}/bin/ruby" ]; then
	# We're already built, yippee!
	exit 0
fi

/usr/local/bin/ruby-build "$1" "$BASEDIR"

chruby-exec "$1" -- gem install bundler
